### ISSUE TITLE
예외 처리

### ISSUE THREAD

**Issue by oxxun21** [oxxun21/read-time#13]
- [x] 독서 시간 기록 같은 날 두번 입력되면 어떻게 할 것 인지 -> 프론트에서 합쳐서 가져오긴 하는데 이걸 DB로 보낼 때 못합치나
- [x] 시간 기록 24시간 넘어감 -> 어케 처리함?
-> 두개 api 분기처리로 해결 ㅋㅋ
- [x] alert 유지?
- [x] 패드에서 테스트 필요
- [x] 독서 시간 삭제, 수정은 어떻게 할 것 인지
- [x] 폰트 변경
- [x] seo 관련 태그 추가 -> og 이미지 뜨는지 확인할 것
- [x] console.log 제거
- [x] 404
- [x] post textarea 스크롤바
- [x] 핸드폰,,버전,,,,,,
- [ ] 책 페이지 넘기게 할거임?
- [x] 새로고침하면 달력 안뜸 (useEffect 수정)
- [x] 시간 기록 입력한거 바로 적용 안됨 -> 새로고침 어떡하지?
- [x] 검색 결과 없을 때 안내 메세지 추가

**Comment by jypark38** [comment]
updateOne() 을 이용해서 유저 정보의 시간 업데이트 해보기

**Comment by jypark38** [comment]
클라이언트 컴포넌트 분리해서 navigation 레이아웃은 서버컴포넌트로 만들어보기?
